default_job = "run"
env.CARGO_TERM_COLOR = "always"

[jobs.run]
command = ["cargo", "run", "--features", "bevy/dynamic_linking"]
need_stdout = true
allow_warnings = true
background = false
on_change_strategy = "kill_then_restart"
kill = ["pkill", "-TERM", "-P"]

[keybinds]
r = "jobs:run"
